### ISSUE TITLE
Incorrect formatting?

### ISSUE THREAD

**Issue by jprichardson** [DeeLindesay/format-number-with-string#1]
Input:

``` js
format(0.00000447343434434, '#.######0')
```

I would expect: `"0.0000045"`, but instead receive `"0.4500000"`.

**Comment by DeeLindesay** [comment]
This is a bug in componitable/format-number on which this relies.  I will look at it

**Comment by DeeLindesay** [comment]
See https://github.com/componitable/format-number/pull/8 
When that is merged this issue will be fixed :)

**Comment by jprichardson** [comment]
:+1: Thanks

**Comment by DeeLindesay** [comment]
This is now fixed.  So closing
